pipeline {
  agent any
  stages {
    stage('Build-Test-Package') {
      agent {
        docker { image 'maven:3.9.6-eclipse-temurin-17' }
      }
              steps {
                git branch: 'main', url: 'https://github.com/Hydra2206/jenkins-by-me.git'
                
                dir('contentstack-java-news-web-app-example-master') {
                    sh '''
                      mvn -v
                      mvn clean compile
                      mvn test
                      mvn package -DskipTests
                    '''

                    archiveArtifacts artifacts: 'target/*.jar'
                }
    }
    }
    stage('Docker Build') {
    agent any
    steps {
        dir('contentstack-java-news-web-app-example-master') {
            sh '''
              docker build -t news-webapp:latest .
            '''
        }
    }
}
    }
  post {
    success {
        echo 'Pipeline completed successfully!'
    }
    failure {
        echo 'Pipeline failed!'
    }
}
}
